name: CI/CD

on:
  push:
    branches: [ master, gh-actions ]
  pull_request:
    branches: [ master ]

jobs:
  nethook2:
    name: NetHook2 - ${{ matrix.configuration }}

    strategy:
      matrix:
        configuration: [ Debug ]
      fail-fast: false

    runs-on: windows-2022

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1

    - name: Cache vcpkg
      id: cache-dependencies
      uses: actions/cache@v3
      with:
        path: Resources/NetHook2/vcpkg
        key: vcpkg-${{ hashFiles('Resources/NetHook2/NetHook2/vcpkg.json') }}

    - name: Configure Dependencies
      run: Resources/NetHook2/SetupDependencies.cmd

    - name: Build NetHook2
      run: msbuild /p:Configuration=${{ matrix.configuration }} Resources/NetHook2/NetHook2.sln

    - name: Upload NetHook2
      uses: actions/upload-artifact@v3
      if: matrix.configuration == 'Release'
      with:
        name: NetHook2
        path: 'Resources/NetHook2/Release/*.dll'

